<?php

namespace common\domain\repository;

use common\domain\entity\News;
use yii\base\BaseObject;

/**
 * Class NewsRepository
 *
 * @package common\domain\repository
 */
class NewsRepository extends BaseObject
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array|\yii\db\ActiveRecord[]
     */
    public function findNews()
    {
        $qb = News::find()->select('news.*')->orderBy('createdAt DESC');
        return $qb->all();
    }

    /**
     * @param $id
     * @return News|null
     */
    public function findNew($id)
    {
        $new = News::findOne(['id' => $id]);
        return $new;
    }
}
