<?php

namespace frontend\modules\api\services;

use common\domain\entity\Photo;
use common\domain\repository\PhotoRepository;
use common\domain\repository\PhotoThumbnailRepository;
use common\libraries\web\Request;

/**
 * Class PhotoService
 *
 * @package frontend\modules\api\services
 */
class PhotoService extends BaseService
{
    /** @var PhotoRepository */
    private $repository;

    /** @var PhotoThumbnailRepository */
    private $thumbnailRepository;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->repository = new PhotoRepository();
        $this->thumbnailRepository = new PhotoThumbnailRepository();
    }

    /**
     * @param $photoCategoryId
     * @return array|\yii\db\ActiveRecord[]
     */
    public function getPhotoByCategory($photoCategoryId)
    {
        return $this->repository->findPhotosByCategory($photoCategoryId);
    }

    /**
     * @param $photoId
     * @return array|\yii\db\ActiveRecord[]
     */
    public function getPhotoThumbnail($photoId)
    {
        return $this->thumbnailRepository->findPhotosByPhoto($photoId);
    }

    /**
     * @param $id
     * @return Photo|null
     */
    public function getPhoto($id)
    {
        return $this->repository->find($id);
    }
}
