<?php

namespace console\libraries\db;

/**
 * Class Migration
 * @package common\libraries\db
 */
class Migration extends \yii\db\Migration
{
    /**
     * @var string
     */
    public $tableOptions;

    public function init()
    {
        $this->db = 'dbMigration';
        parent::init(); // TODO: Change the autogenerated stub

        if ($this->db->driverName === 'mysql') {
            $this->tableOptions = 'ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci';
        }
    }

    /**
     * @param $name
     * @return bool
     * @throws \yii\base\NotSupportedException
     */
    public function tableExist($name)
    {
        $tableName = $this->db->getSchema()->getTableSchema($name);

        if ($tableName === null) {
            return false;
        }

        return true;
    }

    /**
     * @param $tableName
     * @param $columnName
     * @return bool
     * @throws \yii\base\NotSupportedException
     */
    public function columnExist($tableName, $columnName)
    {
        $table = $this->db->getSchema()->getTableSchema($tableName);
        if (is_null($table)) {
            return false;
        }
        $column = $table->getColumn($columnName);
        if (is_null($column)) {
            return false;
        }

        return true;
    }
}
