<?php

namespace frontend\modules\api\controllers;

use common\domain\entity\Photo;
use common\domain\entity\Comment;
use common\domain\repository\CommentRepository;
use frontend\modules\api\services\PhotoService;
use Yii;

class CommentController extends BaseController
{
    /** @var PhotoService */
    private $service;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service = new PhotoService();
    }

    /**
     * @param $categoryId
     * @return array|\yii\db\ActiveRecord[]
     */
    public function actionIndex($entityId, $page)
    {
        $request = Yii::$app->request;
        $comments = (new CommentRepository())->findPhotoCommentByEntityId($entityId, $page);
        foreach ($comments as $key => $comment) {
            $comments[$key]['createdAt'] = date('Y-m-d', $comment['createdAt']); 
        }

        return $comments;
    }

    public function actionCreate()
    {
        $comment = new Comment();
        return $comment->createComment($this->request->post());
    }
}
