<?php

namespace frontend\modules\api\controllers;

use common\domain\entity\Photo;
use common\domain\repository\CommentRepository;
use frontend\modules\api\services\PhotoService;
use Yii;

class CommentController extends BaseController
{
    /** @var PhotoService */
    private $service;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service = new PhotoService();
    }

    /**
     * @param $categoryId
     * @return array|\yii\db\ActiveRecord[]
     */
    public function actionIndex()
    {
        $request = Yii::$app->request;
        return (new CommentRepository())->findPhotoCommentByEntityId($request->get('entityId'));
    }
}
