<?php

namespace frontend\modules\api\controllers;

use common\domain\entity\News;
use frontend\modules\api\services\NewsService;
use Yii;

/**
 * Class NewController
 *
 * @package frontend\modules\api\controllers
 */
class NewController extends BaseController
{
    /**
     * @var NewsService
     */
    private $newService;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->newService = new NewsService();
    }

    /**
     * @return array
     */
    public function actionIndex()
    {
        return $this->newService->getNewList();
    }

    /**
     * @param $id
     * @return News|null
     */
    public function actionView($id)
    {
        return $this->newService->getNewById($id);
    }
}