<?php

namespace frontend\modules\api\controllers;

use frontend\modules\api\services\NewsService;
use Yii;

class NewController extends BaseController
{
    /**
     * @var NewsService
     */
    private $newService;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->newService = new NewsService();
    }

    /**
     * @return array
     */
    public function actionIndex()
    {
        return $this->newService->getNewList();
    }

    public function actionView($id)
    {
        return $this->newService->getNewById($id);
    }
}