<?php

namespace frontend\modules\api\controllers;

use common\domain\entity\Photo;
use frontend\modules\api\services\PhotoService;
use Yii;

class PhotoController extends BaseController
{
    /** @var PhotoService */
    private $service;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service = new PhotoService();
    }

    /**
     * @param $categoryId
     * @return array|\yii\db\ActiveRecord[]
     */
    public function actionIndex($categoryId)
    {
        return $this->service->getPhotoByCategory($categoryId);
    }

    /**
     * @param $id
     * @return Photo|null
     */
    public function actionView($id)
    {
        return $this->service->getPhoto($id);
    }

    /**
     * @param $id
     * @return array|\yii\db\ActiveRecord[]
     */
    public function actionThumbnail($id)
    {
        return $this->service->getPhotoThumbnail($id);
    }
}
